from wtforms import Form, StringField, IntegerField, validators, TextAreaField, FileField

class ContactForm(Form):
 name = StringField('Name', [validators.required(), validators.Length(max = 50)])
 email = StringField('Email Address', [validators.required(), validators.Email(message = 'Enter a valid email id')])
 info = TextAreaField('Info', [validators.required(), validators.Length(max = 500)])
 speciality = StringField('Speciality', [validators.required()])
 college_name = StringField('College', [validators.required()])
 start_date_edu = StringField('Start Date', [validators.required()])
 end_date_edu = StringField('End Date', [validators.required()])
 clinic_exp = StringField('Clinic', [validators.required()])
 start_date_exp = StringField('Start Date', [validators.required()])
 end_date_exp = StringField('End Date', [validators.required()])
 clinic_name = StringField('Clinic Name', [validators.required()])
 fees = IntegerField('Fee', [validators.required()])
 first_addr = StringField('House Number & Street', [validators.required()])
 locality = StringField('Locality', [validators.required()])
 city = StringField('City', [validators.required()])
 pincode = StringField('Pin Code', [validators.required()])
 start_day_booking = StringField('From Day', [validators.required()])
 end_day_booking = StringField('To Day', [validators.required()])
 contact_num = StringField('Contact Number', [validators.required()])
 image = FileField(u'Image File')
 country = StringField('Country', [validators.required()])